# Generated by Django 5.1.4 on 2025-01-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_instructor_alter_course_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='description',
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='yt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
