# Generated by Django 5.1.4 on 2025-01-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_course_lectures_alter_coursedetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=100, null=True),
        ),
    ]
