# Generated by Django 5.1.4 on 2025-01-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_course_lang_course_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
