# Generated by Django 5.1.4 on 2025-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='John Doe', max_length=500),
        ),
    ]
