# Generated by Django 5.1.4 on 2025-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
